### ISSUE TITLE
Map View - infinite scroll happens when I barely scroll from the beginning

### ISSUE THREAD

**Issue by kristen** [jamietsao/codepath-mapstagram#103]
I'm noticing that when I *start* scrolling the collection view at the bottom of the map view, more images are loaded in. I'm not even close to the end of the list. I think the infinite scroll calculations might be off. It makes the app freeze for a second and then the map view constantly gets loaded up with more pictures.

**Comment by jamietsao** [comment]
Yeah I noticed the same.  It freezes a little with the other views too.  Is it hard to make the infinite scroll work more like pull to refresh (i.e. once you hit the bottom, the refresh control is revealed underneath the view, then the request is made?).  If it is, then forget it, otherwise I think the experience might feel slightly smoother.  I think Twitter does that.

**Comment by mbatilando** [comment]
I'll start looking into this

**Comment by jamietsao** [comment]
I think this issue is probably the most urgent at this point.  The other ones we can demo around, but this one really affects the Map View, which I think is the most important part of our demo.

**Comment by kristen** [comment]
I agree. Maybe we can get all hands on deck to debug this one?

**Comment by mbatilando** [comment]
Took a quick hack at this, but I slightly changed the code and it seems to work (I was calculating the wrong measurements). Could someone double check and see how this works?

```
func scrollViewDidEndDragging(scrollView: UIScrollView, willDecelerate decelerate: Bool) {
        let offset = scrollView.contentOffset
        let bounds = scrollView.bounds
        let size = scrollView.contentSize
        let inset = scrollView.contentInset
        let x = offset.x + bounds.size.width - inset.right
        let w = size.width
        if x > w - 30 {
            loadMoreRows()
        }
    }
```

**Comment by jamietsao** [comment]
I did a quick test, and it seems to work!  It basically feels like the infinite scroll for List/Grid, which can be improved but at least it's consistent.

Your fix makes sense - use x and width instead of y and height. 

Nice job! PR it and we'll merge it.
