### ISSUE TITLE
Make sure profile view of private user works properly

### ISSUE THREAD

**Issue by jamietsao** [jamietsao/codepath-mapstagram#116]
When viewing the profile of a private user (by clicking a comment made by said private user), make sure the profile view loads properly

**Comment by jamietsao** [comment]
Looking into this one as I was getting API errors from Instagram earlier when trying to view the profile of a private user.  Need to fix this.

**Comment by jamietsao** [comment]
The `/user/user-id` endpoint returns `APINotAllowedError` when trying to access a private account, which I guess makes sense.  This means we can't show their posts/following/followers counts.  What's confusing is that on Instagram, those counts are shown even for private users, but I guess they're probably are using an internal API.

I'm gonna work on making the profile view work for private users.  I'm essentially gonna just display their profile image, the follow button, and some text that says "This user is private".  Should I put `0` or `N/A` or just hide the entire stats section?

**Comment by kristen** [comment]
I think we should definitely do this, but I don't know if it is important for the demo. I'm not sure what we should show for the stats section. I want to say don't show anything, but that might look weird.

**Comment by jamietsao** [comment]
Yeah, it's *probably* not needed for the demo - my concern is that we click a commenter who happens to be a private user.  How lucky/unlucky do you feel?

**Comment by kristen** [comment]
I think we should only try clicking on the "caption" because that user is public, or else their photo wouldn't show up

**Comment by jamietsao** [comment]
Yeah, we could certainly do that, although the caption user is basically the user in the header, which we should definitely click to demonstrate.  Maybe we just don't click any commenters as part of our demo (we could mention it).  We'll figure out something.  Should be fairly easy to throw up a private user version of the profile view too.

**Comment by kristen** [comment]
OK, sounds good to me.
