### ISSUE TITLE
Change Radius filter to use default iOS checkmark (accessory view)

### ISSUE THREAD

**Issue by jamietsao** [jamietsao/codepath-mapstagram#122]
@mbatilando - We decided on doing this yeah?

**Comment by mbatilando** [comment]
Yep sounds good

**Comment by mbatilando** [comment]
If I change it to use the ios accessory type here's what it looks like:

![screen shot 2015-03-22 at 4 42 06 pm](https://cloud.githubusercontent.com/assets/1978001/6772126/7a158932-d0b2-11e4-9e6f-b76ea04b4da2.png)

Looks fine, but I was hoping I can change the color, but it seems like I can't (http://stackoverflow.com/questions/7641228/change-color-on-checkmark-in-uitableview).

What do you guys think?

**Comment by jamietsao** [comment]
Hmm, that sucks.  I like how the checkmark looks though but would be good to use our green color.  Should we just find an icon for this off noun project?  We do have unlimited downloads .... =)

**Comment by mbatilando** [comment]
Ooh, the ios7 collection has a checkmark

http://thenounproject.com/term/check-mark/57621

**Comment by kristen** [comment]
@mbatilando you just have to change the tintColor to mapstagramColor

**Comment by kristen** [comment]
I did it in my tip calculator

**Comment by jamietsao** [comment]
Oh cool.

**Comment by mbatilando** [comment]
Nicee! I should probably start looking at how recent StackOverflow answers are.

**Comment by mbatilando** [comment]
#129
