### ISSUE TITLE
Pull to refresh clears out old photos?

### ISSUE THREAD

**Issue by jamietsao** [jamietsao/codepath-mapstagram#141]
I infinite scrolled a few times, which means I had quite a bit of photos in all views.  Then I pulled to refresh to see if there were any new photos, and it seemed to perform a fresh search, clearing out the previous list of photos I had.

**Comment by mbatilando** [comment]
Is it safe for me to pass in a minTimestamp to the API call in loadMedia? I'm assuming that loadMedia is only called in pull to refresh.

**Comment by jamietsao** [comment]
loadMedia is called during the initial load of the app as well, but in that case the array is empty, so your helper method to get minTimestamp should return nil.  So passing nil to loadMedia should work.  Then always do prepend, which should also work for the initial case since you are prepending to an empty array.  I think you just need to make sure SessionService initializes mediaArray to be an empty array initially.

**Comment by mbatilando** [comment]
#153
