### ISSUE TITLE
Add infinite scroll feature to all 3 views

### ISSUE THREAD

**Issue by jamietsao** [jamietsao/codepath-mapstagram#28]

**Comment by mbatilando** [comment]
Working on this now

**Comment by jamietsao** [comment]
@mbatilando - Unless you've started on this, I can help with the Instagram API portion.  Basically, adding the extra parameters for min/max ids, etc.  Let me know.

**Comment by mbatilando** [comment]
@jamietsao I already have something in my local copy so it's fine, thanks though

**Comment by jamietsao** [comment]
:+1:

**Comment by mbatilando** [comment]
Done in #92
