### ISSUE TITLE
Fix layout constraint issues

### ISSUE THREAD

**Issue by kristen** [jamietsao/codepath-mapstagram#53]
I have been noticing we have layout constraint issues. I wanted to put this in here as a reminder for me to go through and fix it at the end. I don't know if it makes sense to do it now and possibly create merge conflicts. And then I might have to do it again when we change our views.

**Comment by jamietsao** [comment]
Yeah, we definitely have layout issues.  I kinda figured it would be part of polish since that's when we'll focus on the UI details.

**Comment by jamietsao** [comment]
Hmm, is this as simple as using UIAutomaticDimension?  I believe we're not doing that right now - shouldn't we?
