### ISSUE TITLE
Polish List View

### ISSUE THREAD

**Issue by jamietsao** [jamietsao/codepath-mapstagram#65]
- Fix layout constraint issue
- Fix header disappearing when liking/unliking
- Add heart/broken heart animation when liking/unlking
- Reduce spacing on comments
- ~~usernames should go to profile view~~ #51 
- Add bottom border to header
- ~~Add time icon to header~~ #74 

- BONUS: make comments wrap under username
- BONUS: show likers usernames
- BONUS: show table view of likers

**Comment by kristen** [comment]
starting this

**Comment by jamietsao** [comment]
Can you change the image to use the standard resolution url?  Should be a one-liner.

**Comment by kristen** [comment]
definitely. Good thinking
