### ISSUE TITLE
Polish Search View

### ISSUE THREAD

**Issue by jamietsao** [jamietsao/codepath-mapstagram#68]
- Add search icon
- Radius
 - Leave header when showing options
 - Add selected & unselected icons
 - Change selections to 3 miles, 2 miles, 1 mile, 2 block options (TBD)
- Use different cell when location doesn't have bottom description
- Adjust table view height
- Add HUD progress indicator
- Pre fill Location/Radius with data from last search

**Comment by mbatilando** [comment]
Most of this should be in #84
