### ISSUE TITLE
Make 3 evenly sized grid cells across device sizes

### ISSUE THREAD

**Issue by jamietsao** [jamietsao/codepath-mapstagram#77]
This applies to grid view and profile view

**Comment by jamietsao** [comment]
I'm gonna spend some time tonight to see if I can figure this one out

**Comment by jamietsao** [comment]
Woot, I found a solution that works: http://stackoverflow.com/questions/16272216/uicollection-view-adjust-cell-size-for-screen-size

I just need to perform the calculations and return the proper size depending on the frame size.  Yay!

**Comment by kristen** [comment]
I thought it was going to be that easy. Nice!
