### ISSUE TITLE
Radius is not passed to API call

### ISSUE THREAD

**Issue by jamietsao** [jamietsao/codepath-mapstagram#85]
I hardcoded the radius to nothing (which means we're using the default) in InstagramClient.  We should use whatever value is selected in the search.

**Comment by mbatilando** [comment]
Are we talking about
```
func searchMedia(lat: Double, lng: Double, distance: Double, onComplete: (media: [Media]!, error: NSError!) -> Void)
```
since distance isn't actually used in the func?

**Comment by jamietsao** [comment]
Yup, distance isn't currently passed to API.  Need to fix that and then supply distance to invocations of this call.

**Comment by mbatilando** [comment]
#129
