### ISSUE TITLE
Display caption in List View

### ISSUE THREAD

**Issue by jamietsao** [jamietsao/codepath-mapstagram#89]
I don't believe we're currently displaying a photo's caption in the List View.  Instagram displays it as part of the comments section (1st comment basically).

**Comment by kristen** [comment]
I was wondering about this. Is it called caption in the media object? I can add it to the list view pretty easily

**Comment by jamietsao** [comment]
Yup, it's called `caption`, and has a type of `Comment` which is how Instagram models it.

**Comment by kristen** [comment]
Perfect. Thank you.
